apiVersion: "apps/v1alpha1"
kind: PetSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "fullname" . }}
  replicas: {{ .Values.replicas }} 
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: ELASTICSEARCH_PORT
          value: {{ .Values.elasticsearchPort  | quote }}
        - name: ELASTICSEARCH_NODEPORT
          value: {{ .Values.elasticsearchNodePort  | quote }}
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: {{ .Values.elasticsearchClusterName  | quote  }}
        - name: ELASTICSEARCH_CLUSTER_HOSTS
          value: {{ template "fullname" . }}-0.{{ template "fullname" . }}.{{ .Release.Namespace  }}.svc.cluster.local, {{ template "fullname" . }}-1.{{ template "fullname" . }}.{{ .Release.Namespace  }}.svc.cluster.local, {{ template "fullname" . }}-2.{{ template "fullname" . }}.{{ .Release.Namespace  }}.svc.cluster.local
        - name: ELASTICSEARCH_CLIENT_NODE
          value: {{ .Values.elasticsearchClientNode | quote  }}
        - name: ELASTICSEARCH_NODE_NAME
          value: {{ default ""  .Values.elasticsearchNodeName | quote  }}
        ports: 
        - name: http
          containerPort: {{ .Values.elasticsearchPort }}
          protocol: "TCP"
        - name: node2node 
          containerPort: {{ .Values.elasticsearchNodePort }}
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: {{ template "fullname" . }}
          mountPath: "/bitnami/elasticsearch"
  volumeClaimTemplates:
  - metadata:
      name: {{ template "fullname" . }}-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: {{ .Values.persistence.storageClass }}
    spec:
      accessModes: [ {{ .Values.persistence.accessMode }}   ]
      resources:
        requests:
          storage:  {{ .Values.persistence.size }}
