name: moodle
version: 0.1.0
description: Moodle is a learning platform designed to provide educators, administrators and learners with a single robust, secure and integrated system to create personalised learning environments
keywords:
- moodle
- learning
- php
home: http://www.moodle.org/
sources:
- https://github.com/bitnami/bitnami-docker-moodle
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
icon: https://moodle.org/theme/image.php/moodleorgcleaned_moodleorg/theme_moodleorgcleaned/1479806622/moodle-logo
